### ISSUE TITLE
Finding optimal alpha and beta

### ISSUE THREAD

**Issue by Marcin-Kot-4** [BioMojoLLC/DeepSpeech_BioMojo#1]
Hi,
I'am getting a "ModuleNotFoundError: No module named 'deepspeech_training'" while trying to execute command:
python3 lm_optimizer.py --test_files data/bm_test/general-test.csv --checkpoint_dir fine_tuning_checkpoints --n_hidden 2048 --n_trials 6
Do you know how i can fix it? Does value of alpha and beta have significant impact to the transcryption quality? I make the scorer with few different values of alpha and beta and none of that is working. DeepSpeech can't recognize any single word. My file with words contains:
ZERO
JEDEN
DWA
TRZY
CZTERY
PIĘĆ
SZEŚĆ
SIEDEM
OSIEM
DZIEWIĘĆ
DZIESIĘĆ
JEDENAŚCIE
DWANAŚCIE
TRZYNAŚCIE
CZTERNAŚCIE
PIĘTNAŚCIE
SZESNAŚCIE
SIEDEMNAŚCIE
OSIEMNAŚCIE
DZIEWIĘTNAŚCIE
DWADZIEŚCIA
TRZYDZIEŚCI
CZTERDZIEŚCI
PIĘĆDZIESIĄT
SZEŚĆDZIESIĄT
SIEDEMDZIESIĄT
OSIEMDZIESIĄT
DZIEWIĘĆDZIESIĄT
STO
DWIEŚCIE
TRZYSTA
CZTERYSTA
PIĘĆSET
SZEŚĆSET
SIEDEMSET
OSIEMSET
DZIEWIĘĆSET
alphabet.txt:
# Each line in this file represents the Unicode codepoint (UTF-8 encoded)
# associated with a numeric label.
# A line that starts with # is a comment. You can escape it with \# if you wish
# to use '#' as a label.
 
a
ą
b
c
ć
d
e
ę
f
g
h
i
j
k
l
ł
m
n
ń
o
ó
p
q
r
s
ś
t
u
v
w
x
y
z
ź
ż
# The last (non-comment) line needs to end with a newline.

**Comment by RyanHurlbut** [comment]
You just need to run 
```bash
pip3 install --upgrade pip==20.2.2 wheel==0.34.2 setuptools==49.6.0
pip3 install --upgrade -e .
```
from within the DeepSpeech directory to fix the "ModuleNotFoundError: No module named 'deepspeech_training'" issue. 

As for the alpha and beta, just run the optimizer script using your fine tuning checkpoints, and use the default alpha/beta values output from the script.
